name: Webhook Notify

on:
  push:
    branches:
      - development

jobs:
  notify_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook notification
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{"ref": "${{ github.ref }}", "commit_sha": "${{ github.sha }}"}' $WEBHOOK_URL
